---
config:
  layout: dagre
---
flowchart TD
    start["Start"] --> n1["(n1) 商品の選び方・仕様"] & n2["(n2) 設定方法"]
    n2 --> n14["(n14) 購入製品入力"]
    n14 -- 親機 --> n15["(n15) 利用方法"]
    n14 -- 中継機 --> n6["(n6) 中継機として使用"]
    n15 --> n4 & n3 & n5
    n15 -- "中継機として使用" --> n18["(n18) 新機器EasyMesh対応判定"]
    
    n3["(n3) 今までのWi-Fiルーターと交換"] --> n17["(n17) 新機器スマート引っ越し対応判定"]
    n17 -- Yes --> n16["(n16) 旧機種の型番を入力"]
    n17 -- No --> n9["(n9) 無線引っ越し"]
    n16 --> n10["(n10) 旧機器スマート引っ越し対応判定"]
    n10 -- Yes --> n8["(n8) スマート引っ越し"]
    n10 -- No --> n9

    n4["(n4) 故障して買い替え"] --> n11["(n11) 前回スマート引っ越し使用確認"]
    n11 -- Yes --> n8
    n11 -- No --> n9

    n5["(n5) 新規に設置"] --> n12["(n12) 親機設定"]
    n6 --> n18["(n18) 新機器EasyMesh対応判定"]
    n18 -- Yes --> n21["(n21) 旧機種の型番を入力（EasyMesh用）"]
    n18 -- No --> n13["(n13) 中継機設定"]
    n21 --> n19["(n19) 旧機器EasyMesh対応判定"]
    n19 -- "両方対応" --> n20["(n20) EasyMesh設定"]
    n19 -- "どちらか非対応" --> n13
    
    %% 設定完了後のNPS入力画面への遷移
    n8 --> n22["(n22) NPS入力"]
    n9 --> n22
    n12 --> n22
    n13 --> n22
    n20 --> n22
    n22 --> n23["(n23) 完了"]
    
    n2@{ shape: diam}
    n14@{ shape: manual-input}
    n15@{ shape: manual-input}
    n17@{ shape: diam}
    n16@{ shape: manual-input}
    n21@{ shape: manual-input}
    n10@{ shape: diam}
    n11@{ shape: diam}
    n18@{ shape: diam}
    n19@{ shape: diam}
    n8@{ shape: subproc}
    n9@{ shape: subproc}
    n12@{ shape: subproc}
    n13@{ shape: subproc}
    n20@{ shape: subproc}
    n22@{ shape: manual-input}
    n23@{ shape: circle}

